name : test Self hosted runner
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self_hosted
    
    steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name : System info
          run : |
            uname -a
            sw_vers
            python --version

       