# This is a basic workflow to help you get started with Actions

name: Variables in GitHub Actions

# Controls when the workflow will run
on:

  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
    author : master
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        baseapi : http:// baseurl.api/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: All type of variables and Secrets
        run: |
           echo "Workflow Variable | $author has created the api $baseapi which will expire in $expire"
           echo "Config Variable |  Version of app is ${{vars.VERSION}}"
           echo "Secret Variable |  Secret key is ${{secrets.KEY}}"
           echo "Context Variable |  Repository name is ${{github.repository}}"
        env:
            expire : 10 days
          
